title: Erik Zocher
description: "Persönlicher Blog — Design, Technik, Berlin & mehr"
author: Erik Zocher
email: zocher.erik+blog@gmail.com
baseurl: ""
url: "https://erikzocher.github.io"
lang: de
timezone: Europe/Berlin
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
