title: Erik Zocher
description: "Personal blog - Design, Technology, Berlin & more"
tagline: "Design, Technology, Berlin & more"
author: Erik Zocher
email: etor@gmx.de
baseurl: ""
url: "https://erikzocher.github.io"
lang: en
timezone: Europe/Berlin
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
