title: Erik Zocher
description: "Personal blog ,  Design, Technology, Berlin & more"
author: Erik Zocher
email: zocher.erik+blog@gmail.com
baseurl: ""
url: "https://erikzocher.github.io"
lang: en
timezone: Europe/Berlin
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
